# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ehdsixm/work2/vision_tracker

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ehdsixm/work2/vision_tracker/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ehdsixm/work2/vision_tracker/build/CMakeFiles /home/ehdsixm/work2/vision_tracker/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ehdsixm/work2/vision_tracker/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named vision_tracker

# Build rule for target.
vision_tracker: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vision_tracker
.PHONY : vision_tracker

# fast build rule for target.
vision_tracker/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vision_tracker.dir/build.make CMakeFiles/vision_tracker.dir/build
.PHONY : vision_tracker/fast

src/core/detector.o: src/core/detector.cpp.o
.PHONY : src/core/detector.o

# target to build an object file
src/core/detector.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vision_tracker.dir/build.make CMakeFiles/vision_tracker.dir/src/core/detector.cpp.o
.PHONY : src/core/detector.cpp.o

src/core/detector.i: src/core/detector.cpp.i
.PHONY : src/core/detector.i

# target to preprocess a source file
src/core/detector.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vision_tracker.dir/build.make CMakeFiles/vision_tracker.dir/src/core/detector.cpp.i
.PHONY : src/core/detector.cpp.i

src/core/detector.s: src/core/detector.cpp.s
.PHONY : src/core/detector.s

# target to generate assembly for a file
src/core/detector.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vision_tracker.dir/build.make CMakeFiles/vision_tracker.dir/src/core/detector.cpp.s
.PHONY : src/core/detector.cpp.s

src/core/kalman_filter.o: src/core/kalman_filter.cpp.o
.PHONY : src/core/kalman_filter.o

# target to build an object file
src/core/kalman_filter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vision_tracker.dir/build.make CMakeFiles/vision_tracker.dir/src/core/kalman_filter.cpp.o
.PHONY : src/core/kalman_filter.cpp.o

src/core/kalman_filter.i: src/core/kalman_filter.cpp.i
.PHONY : src/core/kalman_filter.i

# target to preprocess a source file
src/core/kalman_filter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vision_tracker.dir/build.make CMakeFiles/vision_tracker.dir/src/core/kalman_filter.cpp.i
.PHONY : src/core/kalman_filter.cpp.i

src/core/kalman_filter.s: src/core/kalman_filter.cpp.s
.PHONY : src/core/kalman_filter.s

# target to generate assembly for a file
src/core/kalman_filter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vision_tracker.dir/build.make CMakeFiles/vision_tracker.dir/src/core/kalman_filter.cpp.s
.PHONY : src/core/kalman_filter.cpp.s

src/core/pid_controller.o: src/core/pid_controller.cpp.o
.PHONY : src/core/pid_controller.o

# target to build an object file
src/core/pid_controller.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vision_tracker.dir/build.make CMakeFiles/vision_tracker.dir/src/core/pid_controller.cpp.o
.PHONY : src/core/pid_controller.cpp.o

src/core/pid_controller.i: src/core/pid_controller.cpp.i
.PHONY : src/core/pid_controller.i

# target to preprocess a source file
src/core/pid_controller.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vision_tracker.dir/build.make CMakeFiles/vision_tracker.dir/src/core/pid_controller.cpp.i
.PHONY : src/core/pid_controller.cpp.i

src/core/pid_controller.s: src/core/pid_controller.cpp.s
.PHONY : src/core/pid_controller.s

# target to generate assembly for a file
src/core/pid_controller.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vision_tracker.dir/build.make CMakeFiles/vision_tracker.dir/src/core/pid_controller.cpp.s
.PHONY : src/core/pid_controller.cpp.s

src/core/tracker.o: src/core/tracker.cpp.o
.PHONY : src/core/tracker.o

# target to build an object file
src/core/tracker.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vision_tracker.dir/build.make CMakeFiles/vision_tracker.dir/src/core/tracker.cpp.o
.PHONY : src/core/tracker.cpp.o

src/core/tracker.i: src/core/tracker.cpp.i
.PHONY : src/core/tracker.i

# target to preprocess a source file
src/core/tracker.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vision_tracker.dir/build.make CMakeFiles/vision_tracker.dir/src/core/tracker.cpp.i
.PHONY : src/core/tracker.cpp.i

src/core/tracker.s: src/core/tracker.cpp.s
.PHONY : src/core/tracker.s

# target to generate assembly for a file
src/core/tracker.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vision_tracker.dir/build.make CMakeFiles/vision_tracker.dir/src/core/tracker.cpp.s
.PHONY : src/core/tracker.cpp.s

src/hardware/camera.o: src/hardware/camera.cpp.o
.PHONY : src/hardware/camera.o

# target to build an object file
src/hardware/camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vision_tracker.dir/build.make CMakeFiles/vision_tracker.dir/src/hardware/camera.cpp.o
.PHONY : src/hardware/camera.cpp.o

src/hardware/camera.i: src/hardware/camera.cpp.i
.PHONY : src/hardware/camera.i

# target to preprocess a source file
src/hardware/camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vision_tracker.dir/build.make CMakeFiles/vision_tracker.dir/src/hardware/camera.cpp.i
.PHONY : src/hardware/camera.cpp.i

src/hardware/camera.s: src/hardware/camera.cpp.s
.PHONY : src/hardware/camera.s

# target to generate assembly for a file
src/hardware/camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vision_tracker.dir/build.make CMakeFiles/vision_tracker.dir/src/hardware/camera.cpp.s
.PHONY : src/hardware/camera.cpp.s

src/hardware/serial_comm.o: src/hardware/serial_comm.cpp.o
.PHONY : src/hardware/serial_comm.o

# target to build an object file
src/hardware/serial_comm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vision_tracker.dir/build.make CMakeFiles/vision_tracker.dir/src/hardware/serial_comm.cpp.o
.PHONY : src/hardware/serial_comm.cpp.o

src/hardware/serial_comm.i: src/hardware/serial_comm.cpp.i
.PHONY : src/hardware/serial_comm.i

# target to preprocess a source file
src/hardware/serial_comm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vision_tracker.dir/build.make CMakeFiles/vision_tracker.dir/src/hardware/serial_comm.cpp.i
.PHONY : src/hardware/serial_comm.cpp.i

src/hardware/serial_comm.s: src/hardware/serial_comm.cpp.s
.PHONY : src/hardware/serial_comm.s

# target to generate assembly for a file
src/hardware/serial_comm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vision_tracker.dir/build.make CMakeFiles/vision_tracker.dir/src/hardware/serial_comm.cpp.s
.PHONY : src/hardware/serial_comm.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vision_tracker.dir/build.make CMakeFiles/vision_tracker.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vision_tracker.dir/build.make CMakeFiles/vision_tracker.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vision_tracker.dir/build.make CMakeFiles/vision_tracker.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/utils/config_manager.o: src/utils/config_manager.cpp.o
.PHONY : src/utils/config_manager.o

# target to build an object file
src/utils/config_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vision_tracker.dir/build.make CMakeFiles/vision_tracker.dir/src/utils/config_manager.cpp.o
.PHONY : src/utils/config_manager.cpp.o

src/utils/config_manager.i: src/utils/config_manager.cpp.i
.PHONY : src/utils/config_manager.i

# target to preprocess a source file
src/utils/config_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vision_tracker.dir/build.make CMakeFiles/vision_tracker.dir/src/utils/config_manager.cpp.i
.PHONY : src/utils/config_manager.cpp.i

src/utils/config_manager.s: src/utils/config_manager.cpp.s
.PHONY : src/utils/config_manager.s

# target to generate assembly for a file
src/utils/config_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vision_tracker.dir/build.make CMakeFiles/vision_tracker.dir/src/utils/config_manager.cpp.s
.PHONY : src/utils/config_manager.cpp.s

src/utils/logger.o: src/utils/logger.cpp.o
.PHONY : src/utils/logger.o

# target to build an object file
src/utils/logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vision_tracker.dir/build.make CMakeFiles/vision_tracker.dir/src/utils/logger.cpp.o
.PHONY : src/utils/logger.cpp.o

src/utils/logger.i: src/utils/logger.cpp.i
.PHONY : src/utils/logger.i

# target to preprocess a source file
src/utils/logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vision_tracker.dir/build.make CMakeFiles/vision_tracker.dir/src/utils/logger.cpp.i
.PHONY : src/utils/logger.cpp.i

src/utils/logger.s: src/utils/logger.cpp.s
.PHONY : src/utils/logger.s

# target to generate assembly for a file
src/utils/logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vision_tracker.dir/build.make CMakeFiles/vision_tracker.dir/src/utils/logger.cpp.s
.PHONY : src/utils/logger.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... vision_tracker"
	@echo "... src/core/detector.o"
	@echo "... src/core/detector.i"
	@echo "... src/core/detector.s"
	@echo "... src/core/kalman_filter.o"
	@echo "... src/core/kalman_filter.i"
	@echo "... src/core/kalman_filter.s"
	@echo "... src/core/pid_controller.o"
	@echo "... src/core/pid_controller.i"
	@echo "... src/core/pid_controller.s"
	@echo "... src/core/tracker.o"
	@echo "... src/core/tracker.i"
	@echo "... src/core/tracker.s"
	@echo "... src/hardware/camera.o"
	@echo "... src/hardware/camera.i"
	@echo "... src/hardware/camera.s"
	@echo "... src/hardware/serial_comm.o"
	@echo "... src/hardware/serial_comm.i"
	@echo "... src/hardware/serial_comm.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/utils/config_manager.o"
	@echo "... src/utils/config_manager.i"
	@echo "... src/utils/config_manager.s"
	@echo "... src/utils/logger.o"
	@echo "... src/utils/logger.i"
	@echo "... src/utils/logger.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

